algoritmo "ex048"
// 48) Faça um programa que leia 7 números inteiros e no final mostre o somatório entre eles.

var
numero, soma, contagem: inteiro

inicio

      contagem <- 1
      
       Enquanto contagem <= 7 faca
               Escreva ("Digite um número: ")
               Leia (numero)

               soma <- soma + numero
               
               contagem <- contagem + 1
        fimEnquanto

        Escreva (soma)
fimalgoritmo
