algoritmo "ex006"
// 6) Faça um programa que leia um número inteiro e mostre o seu antecessor e seu sucessor.
//Ex:
//Digite um número: 9
//O antecessor de 9 é 8
//O sucessor de 9 é 10
var num, suc, ant:inteiro

inicio
Escreva ("Digite um número inteiro: ")
Leia (num)
suc<-(num+1)
ant<-(num-1)

Escreval ("O antecessor de ", num, " é ", ant)
Escreva ("O sucessor de ", num, " é ", suc)
fimalgoritmo
