algoritmo "ex004"
// 4) Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório entre eles.
//Ex:
//Digite um valor: 8
//Digite outro valor: 5
//A soma entre 8 e 5 é igual a 13.
var num1, num2, soma:inteiro

inicio
Escreva ("Digite um valor")
Leia(num1)
Escreva ("Digite outro valor")
Leia(num2)
soma<-num1+num2
Escreva ("A soma entre ", num1, " e ", num2, " é igual a ", soma)
fimalgoritmo
